<a href="https://colab.research.google.com/github/RyuJungSoo/2022_winter_ai_study/blob/main/%EC%A3%BC%EC%96%B4%EC%A7%84_%EB%AC%B8%EC%9E%A5%EC%9D%84_'%EB%8B%A8%EC%96%B4'%EB%A1%9C_%ED%86%A0%ED%81%B0%ED%99%94_%ED%95%98%EA%B8%B0%2C_%EC%9B%90_%ED%95%AB_%EC%9D%B8%EC%BD%94%EB%94%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

토큰화

In [1]:
# 텍스트 전처리 함수 text_to_word_sequence() 호출
from tensorflow.keras.preprocessing.text import text_to_word_sequence

# 전처리할 텍스트 정하기
text = '해보지 않으면 해낼 수 없다'

# 해당 텍스트 토큰화
result = text_to_word_sequence(text)
print("\n원문:\n", text)
print("\n토큰화:\n", result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [2]:
# 텍스트 전처리 함수 Tokenizer() 호출
from keras.preprocessing.text import Tokenizer

# 전처리하려는 세 개의 문장 정하기
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다',
        '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
        '토큰화 한 결과는 딥러닝에서 사용할 수 있습니다']

# 토큰화 함수를 이용해 전처리하는 과정
token = Tokenizer() # 토큰화 함수 지정
token.fit_on_texts(docs) # 토큰화 함수에 문장 적용하기

# 각 옵션에 맞춰 단어의 빈도 수를 계산한 결과 출력 (OrderedDict 클래스에 담겨 있는 형태로 출력)
print("\n단어 카운트:\n", token.word_counts) 

print("\n문장 카운트: ", token.document_count)
print("\n각 단어가 몇 개의 문장에 포함되어 있는가:\n", token.word_docs) # 출력되는 순서는 랜덤
print("\n각 단어에 매겨진 인덱스 값:\n", token.word_index) # 각 단어의 빈도수가 높은 순서대로 인덱스가 부여됨


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트:  3

각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'텍스트의': 2, '토큰화': 3, '각': 1, '먼저': 1, '단어를': 1, '나누어': 1, '합니다': 1, '단어로': 1, '인식됩니다': 1, '해야': 1, '딥러닝에서': 2, '사용할': 1, '있습니다': 1, '결과는': 1, '한': 1, '수': 1})

각 단어에 매겨진 인덱스 값:
 {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


원-핫 인코딩

In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer

text = "오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [12]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [13]:
import numpy as np
from keras.utils import np_utils

# 인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index) + 1
x = np_utils.to_categorical(x, num_classes=word_size)

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]
