<a href="https://colab.research.google.com/github/RyuJungSoo/2022_winter_ai_study/blob/main/%EC%98%81%ED%99%94_%EB%A6%AC%EB%B7%B0%EA%B0%80_%EA%B8%8D%EC%A0%95%EC%A0%81%EC%9D%B8%EC%A7%80_%EB%B6%80%EC%A0%95%EC%A0%81%EC%9D%B8%EC%A7%80_%EC%98%88%EC%B8%A1%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding

In [2]:
# 텍스트 리뷰 자료 지정
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다.', '한번 더 보고싶네요', '글쎼요', '별로예요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [3]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index) # 각 단어에 매겨진 인덱스 값 출력
x = token.texts_to_sequences(docs) # 토큰에 지정된 인덱스로 새로운 배열을 생성
print("\n리뷰 텍스트, 토큰화 결과:\n",  x)

# 패딩, 서로 다른 길이의 데이터를 4로 맞춤
padded_x = pad_sequences(x, 4)
print("\n패딩 결과:\n", padded_x)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎼요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}

리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]

패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [4]:
# 임베딩에 입력될 단어 수 지정
word_size = len(token.word_index)+1 # 인덱스 0 때문에 1 더해주기

In [5]:
# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4)) # 총 입력되는 단어의 수는 word_size, 임베딩 후 출력되는 벡터의 크기는 8, 매번 단어 4개씩만 들어가기(패딩 과정을 거쳐 길이를 4로 맞췄기 때문)
model.add(Flatten()) # Dense 레이어를 쓰기 위해 데이터를 1차원으로 변환
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)

print("\n Accuracy: %.4f" %(model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 1s 789ms/step - loss: 0.7008 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6987 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6967 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6947 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6926 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6906 - accuracy: 0.5000
Epoch 7/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6886 - accuracy: 0.6000
Epoch 8/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6866 - accuracy: 0.6000
Epoch 9/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6847 - accuracy: 0.7000
Epoch 10/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6827 - accuracy: 0.7000
Epoch 11/20
1/1 [====================